### ISSUE TITLE
[App] Fix missing digits in moneypool banner

### ISSUE THREAD

**Issue by milanbargiel** [milanbargiel/kulturgenerator#203]
### steps to reproduce
- Navigate to https://staging.kulturgenerator.org/
- Look at moneypool banner
- Observe, that last to digits of moneypool are missing

![missing-digits](https://user-images.githubusercontent.com/21197498/98471903-af7c6e80-21ef-11eb-86ea-f8c3ca95ff3b.png)

**Comment by moritzpflueger** [comment]
### first assumptions
* the data is correct.
* the problem is with rendering.
* has something to do with the calculated width.
* If I turn of width in Chrome Inspector it works (compare screenshots).

![image](https://user-images.githubusercontent.com/65345718/98522570-26a81600-2275-11eb-8cd4-fbba2a31f3d2.png)

![image](https://user-images.githubusercontent.com/65345718/98522593-2e67ba80-2275-11eb-8499-1c45d33196fe.png)
